name: Commit Message Check

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

jobs:
  commit-message-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch the full commit history

    - name: Check Pull Request Title
      run: |
        pattern="^\[[A-Z]*-[0-9]+\] .+"
        pr_title="${{ github.event.pull_request.title }}"

        echo "Pull Request title: $pr_title"
        echo "Pattern: $pattern"
        echo "Match: $([[ $pr_title =~ $pattern ]] && echo "true" || echo "false")"

        if [[ ! $pr_title =~ $pattern ]]; then
          echo "Error: Invalid pull request title. Please follow the expected pattern: [<Project type>-<ticket no.>] <pull request title>"
          echo "For Example: [JIRA-1234] Update README"
          exit 1
        fi
