name: Commit Message Check

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

jobs:
  commit-message-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch the full commit history

    - name: Check Commit Message
      run: |
        pattern="^\[.*-[0-9]+\] .+"
        commit_title=$(git log --format=%s -n 1 ${{ github.event.before || github.sha }})

        echo "Commit title: $commit_title"
        echo "Pattern: $pattern"
        echo "Match: $([[ $commit_title =~ $pattern ]] && echo "true" || echo "false")"

        if [[ "$commit_title" == "Merge"* ]]; then
          echo "Info: Skipping commit message check for merge commit."
        elif [[ ! $commit_title =~ $pattern ]]; then
          echo "Error: Invalid commit message. Please follow the expected pattern: [<Project type>-<ticket no.>] <commit message>"
          echo "For Example: [JIRA-1234] updated example file"
          exit 1
        fi
