name: Commit Message Check

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

jobs:
  commit-message-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.before }}
        fetch-depth: 0  # Fetch the full commit history

    - name: Check Commit Message
      run: |
        pattern="^\[.*-[0-9]+\] .+"
        commit_message=$(git log --format=%B -n 1)

        if [[ ! $commit_message =~ $pattern ]]; then
          echo "Error: Invalid commit message. Please follow the expected pattern: [.*-123] your message here"
          exit 1
        fi
